package cl.hipertrans.entity;
// Generated 30-10-2016 0:16:07 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comuna generated by hbm2java
 */
@Entity
@Table(name="comuna"
    ,catalog="hipertrans"
)
public class Comuna  implements java.io.Serializable {


     private int idComuna;
     private String nombreComuna;

    public Comuna() {
    }

    public Comuna(int idComuna, String nombreComuna) {
       this.idComuna = idComuna;
       this.nombreComuna = nombreComuna;
    }
   
     @Id 

    
    @Column(name="id_comuna", unique=true, nullable=false)
    public int getIdComuna() {
        return this.idComuna;
    }
    
    public void setIdComuna(int idComuna) {
        this.idComuna = idComuna;
    }

    
    @Column(name="nombre_comuna", nullable=false, length=50)
    public String getNombreComuna() {
        return this.nombreComuna;
    }
    
    public void setNombreComuna(String nombreComuna) {
        this.nombreComuna = nombreComuna;
    }




}


